//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEmployee
    {
        public int EmployeeID { get; set; }
        public string EmpName { get; set; }
        public string EmpSurname { get; set; }
        public string EmpCellNo { get; set; }
        public string EmpEmail { get; set; }
        public Nullable<System.DateTime> EmpStartDate { get; set; }
        public Nullable<int> EmpShiftsCompleted { get; set; }
    }
}
