//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditor_Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> CreditorID { get; set; }
        public Nullable<System.DateTime> CredPaymentDate { get; set; }
        public Nullable<float> CredPaymentAmount { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Creditor Creditor { get; set; }
    }
}
