//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Customer_Order = new HashSet<Customer_Order>();
        }
    
        public int CustomerID { get; set; }
        public string CusName { get; set; }
        public string CusSurname { get; set; }
        public string CusCell { get; set; }
        public string CusEmail { get; set; }
        public string CusStreetNr { get; set; }
        public string CusStreet { get; set; }
        public string CusCode { get; set; }
        public string CusSuburb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Order> Customer_Order { get; set; }
    }
}
