//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Recipient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation_Recipient()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int RecipientID { get; set; }
        public string DrName { get; set; }
        public string DrSurname { get; set; }
        public string DrCell { get; set; }
        public string DrEmail { get; set; }
        public string DrStreetNr { get; set; }
        public string DrStreet { get; set; }
        public string DrArea { get; set; }
        public string DrCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
    }
}
