//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donated_Product
    {
        public int ProductID { get; set; }
        public int DonationID { get; set; }
        public Nullable<int> DPQuantity { get; set; }
        public Nullable<int> ContainerID { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual Product Product { get; set; }
        public virtual Container Container { get; set; }
    }
}
