//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationID { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public Nullable<int> LocationStatusID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string LocName { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Container Container { get; set; }
        public virtual Location_Status Location_Status { get; set; }
    }
}
