//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marked_Off
    {
        public int MarkedOffID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> MoQuantity { get; set; }
        public Nullable<System.DateTime> MoDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Marked_Off_Reason Marked_Off_Reason { get; set; }
    }
}
