//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> CustomerOrderID { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<float> PayAmount { get; set; }
    
        public virtual Customer_Order Customer_Order { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
