//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order_Line
    {
        public int CustomerOrderID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> PLQuantity { get; set; }
    
        public virtual Customer_Order Customer_Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
