//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Product
    {
        public int ReturnProductID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual Product Product { get; set; }
    }
}
