//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Take
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_Take()
        {
            this.Marked_Off = new HashSet<Marked_Off>();
            this.Stock_Take_Product = new HashSet<Stock_Take_Product>();
        }
    
        public int StockTakeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public Nullable<System.DateTime> STakeDate { get; set; }
        public Nullable<bool> isCompleted { get; set; }
    
        public virtual Container Container { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marked_Off> Marked_Off { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Take_Product> Stock_Take_Product { get; set; }
        public virtual User User { get; set; }
    }
}
