//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order_Product
    {
        public int ProductID { get; set; }
        public int SupplierOrderID { get; set; }
        public Nullable<int> SOPQuantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
