//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Order()
        {
            this.Supplier_Order_Product = new HashSet<Supplier_Order_Product>();
        }
    
        public int SupplierOrderID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> SupplierOrderStatusID { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public Nullable<int> ContainerID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Order_Product> Supplier_Order_Product { get; set; }
        public virtual Supplier_Order_Status Supplier_Order_Status { get; set; }
        public virtual Container Container { get; set; }
    }
}
