//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORDRA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Type_Access
    {
        public int UserAccessID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> AccessID { get; set; }
        public Nullable<System.DateTime> AccessGranted { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual User_Type User_Type { get; set; }
    }
}
